GLOBAL ActiveConfigOnStartup 1
GLOBAL StartInTraybar

[CONFIG_1]
OPTION configName ctrl-ime

# HHKB special keys -> Ctrl
# tap時だけ AHK に IME 切替要求
REWIRE NOCONVERT LCTRL F22
REWIRE CONVERT   RCTRL F23

# US layout: ; / : swap
COMBO ; [^^^^ ^^^^] > combo(LSHF+;)
COMBO ; [^^^^ ^^^&] > moddedKey(; + ....)
COMBO ; [^^^& ^^^^] > moddedKey(; + ....)
COMBO ; [^^^& ^^^&] > moddedKey(; + ....)
