GLOBAL ActiveConfigOnStartup 1

[CONFIG_1]
OPTION configName ctrl-ime

# Ctrl tap -> AHK -> IME_SET()
REWIRE LCTRL LCTRL F22
REWIRE RCTRL RCTRL F23

# ----------------------------------------
# US layout: ; / : swap
# ----------------------------------------

# ; -> :
COMBO ; [^^^^ ^^^^] > combo(LSHF+;)

# Shift + ; -> ;
COMBO ; [^^^^ ^^^&] > moddedKey(; + ....)
COMBO ; [^^^& ^^^^] > moddedKey(; + ....)

# Both Shift
COMBO ; [^^^& ^^^&] > moddedKey(; + ....)

