[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1

    if has('nvim')
      source ~/.config/nvim/vimrcs/deoplete.vim
    else
      source ~/.vim/vimrcs/deoplete.vim
    endif
'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-dictionary'
depends = ['Shougo/deoplete.nvim']

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
hook_add = '''

    if has('nvim')
      source ~/.config/nvim/vimrcs/denite.vim
    else
      source ~/.vim/vimrcs/denite.vim
    endif
'''

[[plugins]] # denite file_mru source require this
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'himanoa/denite-git-grep'
depends = ['Shougo/denite.nvim']

[[plugins]] # high performance yank
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
    if has('nvim')
      source ~/.config/nvim/vimrcs/neosnippets.vim
    else
      source ~/.vim/vimrcs/neosnippets.vim
    endif
'''

# Color scheme
[[plugins]]
repo = 'w0ng/vim-hybrid'

# Color scheme
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # 囲むやつ
repo = 'tpope/vim-surround'

[[plugins]] # coloring ansi code
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]] # non blocking lint tool
repo = 'w0rp/ale'
hook_add = '''

    if has('nvim')
      source ~/.config/nvim/vimrcs/ale.vim
    else
      source ~/.vim/vimrcs/ale.vim
    endif
'''

[[plugins]] # コメントON/OFFを手軽に実行
repo = 'tomtom/tcomment_vim'
hook_add = '''
    if has('nvim')
      source ~/.config/nvim/vimrcs/tcomment.vim
    else
      source ~/.vim/vimrcs/tcomment.vim
    endif
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''

    if has('nvim')
      source ~/.config/nvim/vimrcs/nerdtree.vim
    else
      source ~/.vim/vimrcs/nerdtree.vim
    endif
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

###fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap <silent> <Leader>g :<C-u>silent call <SID>find_rip_grep()<CR>

  function! s:find_rip_grep() abort
      call fzf#vim#grep(
                  \   'rg --ignore-file ~/.ignore --column --line-number --no-heading --hidden --smart-case .+',
                  \   1,
                  \   fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%', '?'),
                  \   0,
                  \ )
  endfunction
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
