# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = 'go'
# hook_add = '''
#  source ~/.config/nvim/vimrcs/vim-go.vim
# '''

# go completion
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
rev = 'next'
on_ft = ['go']
# hook_add = '''
#     let g:LanguageClient_settingsPath = "~/.config/nvim/settings.json"
# '''

hook_source = '''
    source ~/.config/nvim/vimrcs/lsp.vim
    source ~/.config/nvim/vimrcs/go_alternate.vim
    source ~/.config/nvim/vimrcs/go.vim
'''
